spring.application.name=demo
server.port=8081
# 1. Dirección de tu base de datos (asegúrate de que la DB 'libreria_db' exista en MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/libreria_db?useSSL=false&serverTimezone=UTC

# 2. Tus credenciales de MySQL
spring.datasource.username=root
spring.datasource.password=

# 3. Driver de conexión
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 4. Hibernate: 'update' crea las tablas automáticamente si no existen
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

